---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data("rest_inspec")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
  rest_inspec %>%
  sample_n(2500)%>%
  filter(boro == "MANHATTAN")%>%
  filter(critical_flag != "Not Applicable")%>%
  mutate(text_label = critical_flag)%>%
  drop_na(score)%>%
  drop_na(grade)%>%
  select(grade, score, critical_flag, text_label)%>%
  plot_ly(
    x = ~ grade, y = ~score, type = "box", mode = "markers",
    color = ~critical_flag, text = ~text_label, alpha = 0.5)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
  rest_inspec %>%
  sample_n(2500)%>%
  mutate(text_label = boro)%>%
  drop_na(inspection_date)%>%
  drop_na(score)%>%
  arrange(inspection_date)%>%
  select(inspection_date, score, boro, text_label)%>%
  plot_ly(
    x = ~ inspection_date, y = ~score, type = "scatter", mode = "markers",
    color = ~boro, text = ~text_label, alpha = 0.5)
```

### Chart C

```{r}
  rest_inspec %>%
  sample_n(2500)%>%
  drop_na(cuisine_description)%>%
  arrange(cuisine_description)%>%
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n))%>%
  plot_ly(
    x = ~ cuisine_description, y = ~n, type = "bar",  color = ~cuisine_description, colors = "viridis", showlegend=FALSE)
```

