---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Education

<b>University of Texas at Austin</b>

BSA Biology Honors with Elements of Computing Certificate and Pre-Health Professions Certificate (Graduated May 2019)

Health Science Scholars Honors Program

<b>Columbia University Mailman School of Public Health</b>

MPH Epidemiology and Applied Biostatistics Certificate (Graduating May 2021)

### Research Experience

●	Undergraduate research assistant in Dr. Martin Poenie’s Cellular Biology lab. Worked on a research project studying the role of DISC1 in T-cell activation. Culminated my research into an independent Capstone Thesis. Integrated my thesis with relevant findings in the lab to publish a paper in the Journal of Cell Science - 10 hours/week. 3 years [650 hours]
(https://doi.org/10.1242/jcs.242875)

●	Summer research internship with a nutrition team in Chennai, India studying the impact of maternal characteristics on the dietary pattern of school children. Research abstract was selected for a poster presentation at the 15th Annual Apollo International Clinical Nutrition Conference in Sri Lanka - 16 hours/week. Summer 2016. [64 hours]

●	Clinical observation and research internship at the Nithra Institute of Sleep Sciences in  Chennai, India. Involved in a research project studying the gender differences in acceptance of treatment for sleep apnea which was submitted as a research abstract to SLEEP 2018, Annual Conference of the American Academy of Sleep Medicine - 15 hours/week. Summer 2017 [45 hours]               (https://doi.org/10.1093/sleep/zsy061.522)

### Volunteer Work/ Community Service

●	Ambassador for the Love Strength & Hope organization at the Austin City Limits (ACL) music festival [12 hours]

●	Volunteer at the Micah 6 food pantry to serve food to homeless people in the Austin community [16 hours]

●	Volunteered to create awareness at the Multiple sclerosis bike race [10 hours]

●	Volunteered in the organizing committee for the Congenital Texas heart walk by the American Heart Association [18 hours]

●	Volunteered as an usher at UT football games as part of the American Chemical Society to raise money for cancer research [8 hours]

●	Volunteered to build a haunted house to raise money for cancer related charities and organizations as part of ‘Scare for a Cure’  [21 hours]

●	Ambassador for SAGA charitable trust to educate the general public on basic life saving skills [30 hours]

●	Educated and Empowered women as a volunteer for the NAAM Foundation [24 hours]

●	Event chairperson and exam proctor at the Austin Regional Science Olympiad [20 hours] 

●	Volunteered for the “Exploring the Human Body” event at Explore UT 2018 [8 hours]

●	Volunteer at HOPE clinic for the underserved. Engaged as a triage assistant, medical scribe and a front-desk attendant. [65 hours]

●	Global Impact Fellow for Unite for Sight. Raised 1800 dollars for the organization to provide free reading glasses to underserved communities in Southern India. Involved in global outreach camps and helped with visual acuity screening [84 hours]

●	Volunteer for the COVID-19 Student Service Corps (CSSC). Involved in the “Hero Meals” division where I help coordinate delivery of food to physicians and patients being treated at the Columbia Irving Medical Center [30 hours]

### Work Experience

●	Interned at ‘Unislink’, a healthcare analytics company. Worked on a project where I analyzed clinical quality measures and helped develop a Java based application that presents patient data to physicians [6 weeks - 40 hours/week. Summer 2019]

●	 HRTP Intern at the New York City Department of Health. Worked in the Surveys and Data Analytics Unit of the Epidemiology Bureau on COVID-19 Health and Social Determinants of Health surveys for the Healthy NYC Project [20 hours/week. Spring and Summer 2020]

●	Teaching Assistant for the Quantitative Research Methods course at the Mailman School of Public Health at Columbia University [15 hours/week. Fall 2020]

### Extracurricular Activities

●	Member of the ‘Soul Blend’ acapella group at the University of Texas. Performed at the ‘Acapalooza’ event to raise money for ‘Voices Against Violence’. Held an officer position in the organization for a semester and was a member of the group for one year 

●	Shadowed doctors from various specialties at Apollo Hospitals, India during the summer of 2016 and again during the summer of 2018 [54 hours]

●	Participated in a shadowing program by the Johns Hopkins Hospital that involved shadowing Dr. Joseph Sakran and his team in the Johns Hopkins Surgical ICU followed by a week of shadowing at the University of Maryland Medical Center (UMMC) [72 hours]

●	Studied abroad in Seville, Spain during the summer of 2017. Studied Evolution and Spanish culture as part of the ‘Evolution: An International and Cultural Perspective’ University of Texas study abroad program

●	Ambassador and mentor for the Health Science Scholars honors program.

●	Event organizer and exam proctor for the Thermodynamics event at the Austin Regional Science Olympiad

### Awards and Certifications

●	Recipient of the ‘Ralph. A. Steiner M.D scholarship’

●	Cleared all 8 grades of the Trinity College of London professional level piano examinations with merit

●	Member of the ‘Alpha Lambda Delta’ and ‘Phi Eta Sigma’ honor societies

●	Recipient of the ‘Collegiate Scholar’ award by the University of Texas

●	Completed the ‘Heartsaver CPR and AED provider’ certification by the American Heart Association

●	Completed the Johns Hopkins Patient Safety Certification Program by the Armstrong Institute for Patient Safety and Quality

### Skills

●	Can speak 4 languages - English, Hindi, Sanskrit and Tamil. Fluent in English and Tamil

●	Played tennis in the school level and volleyball in the intramural college level.

●	Can code in Python, R Studio, Swift, HTML, Javascript and Java programming languages. Have basic skills in app development, graphic design, data analytics and web programming.

●	Studied piano for 8 years. Can read and write sheet music.

